name: Phoebus build

on: 
  push:
    branches-ignore:
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Maven and Java Action
      uses: s4u/setup-maven-action@v1.18.0
      with:
        java-version: '17'
        maven-version: '3.9.6'
    - name: Build
<<<<<<< HEAD
      run: mvn --batch-mode install -DskipTests
=======
      run: mvn -DskipTests --batch-mode install
>>>>>>> 07a2b3d51 (Update build.yml)
